dataset: path
data_folder: crop_identification
image_size: 32
batch_size: 256
num_workers: 8

model: supcon
model_args:
    encoder: resnet50
    load_pt_encoder: True
load:

epochs: 1000
# optimizer: sgd
# optimizer_args:
#     lr: 0.05
#     momentum: 0.9
#     weight_decay: 0.0001
optimizer: adam
optimizer_args:
#     lr: 0.001

scheduler: exp

print_freq: 20
save_freq: 50



